### ISSUE TITLE
Input `/re` crashes kbtui

### ISSUE THREAD

**Issue by haukened** [Rudi9719/kbtui#13]
## problem
typing `/re` into the input box crashes the program.

## stack trace
```
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.cmdReply(0xc00037ed30, 0x1, 0x1)
        /home/david/github/kbtui/cmdReply.go:24 +0x33b
main.handleInput(0x5865c1, 0x5, 0x28, 0x5)
        /home/david/github/kbtui/main.go:478 +0x355
main.initKeybindings.func3(0xc000192000, 0xc0001be360, 0x5, 0xc000000101)
        /home/david/github/kbtui/main.go:134 +0x36
github.com/awesome-gocui/gocui.(*Gui).execKeybinding(...)
        /home/david/.go/src/github.com/awesome-gocui/gocui/gui.go:747
github.com/awesome-gocui/gocui.(*Gui).execKeybindings(0xc000192000, 0xc0001be360, 0xc00012fd68, 0x4, 0x5, 0xc0001be480)
        /home/david/.go/src/github.com/awesome-gocui/gocui/gui.go:733 +0x110
github.com/awesome-gocui/gocui.(*Gui).onKey(0xc000192000, 0xc00012fd68, 0x2, 0x0)
        /home/david/.go/src/github.com/awesome-gocui/gocui/gui.go:694 +0x164
github.com/awesome-gocui/gocui.(*Gui).handleEvent(...)
        /home/david/.go/src/github.com/awesome-gocui/gocui/gui.go:455
github.com/awesome-gocui/gocui.(*Gui).MainLoop(0xc000192000, 0x0, 0xc00010ff20)
        /home/david/.go/src/github.com/awesome-gocui/gocui/gui.go:415 +0x202
main.main()
        /home/david/github/kbtui/main.go:51 +0x372
```

**Comment by Rudi9719** [comment]
Fixed in [dev d071564](https://github.com/Rudi9719/kbtui/commit/d07156402bca8db528382448fb9a756a2417ece1)
